version: "3"
services:
  db:
    image: mysql:8.0.26
    restart: always
    command:
      - --lower_case_table_names=1
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_ROOT_PASSWORD=root1234!!
      - TZ=Asia/Seoul
    volumes:
      - C:\TEMP\MYSQL:/var/lib/mysql
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - C:\TEMP\redis:/var/lib/redis
    command: [ "redis-server", "--requirepass", "root1234!!" ]
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ports:
      - "9200:9200"
    volumes:
      - ./es-data:/usr/share/elasticsearch/data  # 데이터 저장
      - ./dict:/usr/share/elasticsearch/config/dict  # 사용자 사전 마운트
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.3
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
volumes:
  elastic_data:

#  user-service:
#    image: user-service-image
#    depends_on:
#      - user-db
#    ports:
#      - "8081:8081"
#  user-db:
#    image: mysql:latest
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: user_db
#    ports:
#      - "3306:3306"
#
#  book-service:
#    image: book-service-image
#    depends_on:
#      - book-db
#    ports:
#      - "8082:8082"
#  book-db:
#    image: mysql:latest
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: book_db
#    ports:
#      - "3307:3306"
#
#  order-service:
#    image: order-service-image
#    depends_on:
#      - order-db
#    ports:
#      - "8083:8083"
#  order-db:
#    image: mysql:latest
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: order_db
#    ports:
#      - "3308:3306"
